name: Build and Deploy Vue App

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # دریافت سورس پروژه
      - name: Checkout
        uses: actions/checkout@v4

      # نصب Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      # نصب دقیق نسخه‌های package-lock.json
      - name: Install dependencies
        run: npm ci

      # Build پروژه
      - name: Build
        run: npm run build

      # تنظیم GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # آپلود پوشه dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      # Deploy روی GitHub Pages
      - name: Deploy
        uses: actions/deploy-pages@v4